source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'mavryc' do

  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 3.1.1'
  pod 'Locksmith', '~> 3.0'

  target 'mavrycTests' do
    pod 'SwiftyJSON', '~> 3.1.1'
  end

end
